config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Pwa::Engine, at: ''

  scope 'app' do
    resources :quantities, only: [:index, :show] do
      get 'units_of_measurement', to: 'unit_of_measurements#index'
    end
    resources :unit_of_measurements, path: 'units', only: [:show]
    resources :constants, only: [:show]
    resources :equations, only: [:show]
    resources :calculations, except: [:new] do
      get 'share', to: 'calculations#share', constraints: Modalist::Ajax.new
      resources :measurements, only: [:show, :update],
                               controller: 'calculations/measurements'
    end
    get 'what', to: 'calculations#what'
    get 'how', to: 'calculations#how'
    get 'measurements', to: 'calculations#measurements'

    resources :categories, only: [:index, :show]
    resources :packs, only: [:show] do
      get 'checkout', to: 'packs#checkout', constraints: Modalist::Ajax.new
    end

    resources :purchases, only: [:create]

    devise_for :users, path: '', controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
    }, path_names: {
      sign_in: 'signin',
      sign_up: 'signup',
      sign_out: 'signout',
      password: 'forgot',
      edit: 'account'
    }

    get 'search', to: 'search#index'

    get 'setup', to: 'welcome#setup'
    get 'language', to: 'welcome#language', constraints: Modalist::Ajax.new

    root 'calculations#new', as: :app_root
  end

  root 'welcome#index'

  match '*path', to: 'r404#not_found', via: :all
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  layout 'mozaic', only: [:setup]

  def index
    turbolinks_animate 'fadein'
  end

  def setup
    turbolinks_animate 'fadein'
    redirect_to app_root_url if already_setup?
    session[:setup] = true
  end

  def language
    modalist
  end

  private

  def already_setup?
    !params[:stay] && (current_user || session[:setup])
  end
end

app/views/welcome/drafts.haml
%h1 Welcome#drafts
%p Find me in app/views/welcome/drafts.html.haml

app/views/welcome/index.html.haml
- meta title: t('welcome.index.title')

%section#head
  .content-wrapper
    %h1= t('welcome.index.header')
    %h2= t('welcome.index.subheader')
    .myg-button__container
      = link_to t('d.install'), 'Settings.phylator.socials.nativegap', target: '_blank', class: 'myg-button'
      = link_to t('welcome.index.open_web_app'), (current_user ? app_root_url : setup_url), class: 'myg-button--secondary'
  .image-wrapper
    = image_tag 'templates/welcome/app.png'

app/views/welcome/language.html.haml
= component 'modalist', title: t('welcome.language.title') do
  = component 'modalist/closer'

%p= link_to 'Deutsch', url_without_parameters(url_for(:back)) + '?locale=de'
%p= link_to 'English', url_without_parameters(url_for(:back)) + '?locale=en'

app/views/welcome/setup.html.haml
.myg-slide.main-carousel
  .carousel-cell
    %h1.sm= t('welcome.setup.slide1.title')
    %p.lg= t('welcome.setup.slide1.content')
  .carousel-cell
    %h1.sm= t('welcome.setup.slide2.title')
    %p.lg= t('welcome.setup.slide2.content')
  .carousel-cell
    %h1.sm= t('welcome.setup.slide3.title')
    %p.lg= t('welcome.setup.slide3.content')
    .myg-button__container
      - if current_user
        = link_to t('welcome.setup.slide3.get_started'), app_root_url, class: 'myg-button'
      - else
        = link_to t('d.signin'), new_user_session_url, class: 'myg-button'
        = link_to t('welcome.setup.slide3.get_started'), app_root_url, class: 'myg-button--secondary'