config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Pwa::Engine, at: ''

  scope 'app' do
    resources :quantities, only: [:index, :show] do
      get 'units_of_measurement', to: 'unit_of_measurements#index'
    end
    resources :unit_of_measurements, path: 'units', only: [:show]
    resources :constants, only: [:show]
    resources :equations, only: [:show]
    resources :calculations, except: [:new] do
      get 'share', to: 'calculations#share', constraints: Modalist::Ajax.new
      resources :measurements, only: [:show, :update],
                               controller: 'calculations/measurements'
    end
    get 'what', to: 'calculations#what'
    get 'how', to: 'calculations#how'
    get 'measurements', to: 'calculations#measurements'

    resources :categories, only: [:index, :show]
    resources :packs, only: [:show] do
      get 'checkout', to: 'packs#checkout', constraints: Modalist::Ajax.new
    end

    resources :purchases, only: [:create]

    devise_for :users, path: '', controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords'
    }, path_names: {
      sign_in: 'signin',
      sign_up: 'signup',
      sign_out: 'signout',
      password: 'forgot',
      edit: 'account'
    }

    get 'search', to: 'search#index'

    get 'setup', to: 'welcome#setup'
    get 'language', to: 'welcome#language', constraints: Modalist::Ajax.new

    root 'calculations#new', as: :app_root
  end

  root 'welcome#index'

  match '*path', to: 'r404#not_found', via: :all
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  translates :name, :description

  has_many :packs

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true

  def purchased?(user)
    purchased_packs = purchased_packs_count(user)

    if purchased_packs == packs.count
      0
    elsif purchased_packs.positive?
      1
    else
      2
    end
  end

  private

  def purchased_packs_count(user)
    purchased_packs = 0
    packs.each do |pack|
      next unless pack.purchased?(user) || pack.price.zero?

      purchased_packs += 1
    end
    purchased_packs
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_categories, only: [:index]
  before_action :set_category, only: [:show]
  before_action :set_packs, only: [:show]

  layout 'app', only: [:index]
  layout 'app/show', only: [:show]

  def index
    turbolinks_animate 'fadein'
  end

  def show
    turbolinks_animate 'fadeinright'
  end

  private

  def set_categories
    @categories = Category.all.with_translations(I18n.locale).order(:name)
    authorizes! :read, @categories
  end

  def set_category
    @category = Category.friendly.find(params[:id])
    authorize! :read, @category
  end

  def set_packs
    @packs = @category.packs.order(:price)
    authorizes! :read, @packs
  end
end

app/views/categories/_category.html.haml
= link_to category, class: 'myg-card', data: { turbolinks_animate_animation: local_assigns[:animation] } do
  %h3= category.name
  %p.flex.center--c
    - if category.purchased?(current_user).zero?
      %i.nc-icon.nc-check-circle-08
      %span= t('categories.category.added')
    - elsif category.purchased?(current_user) == 1
      %i.nc-icon.nc-e-check
      %span= t('categories.category.partially_added')
    - else
      %i.nc-icon.nc-e-circle
      %span= t('categories.category.not_added')

app/views/categories/index.html.haml
- meta title: t('d.packs')

.title
  %h1.sm= t('d.packs')
  = link_to search_url(tab: 'pack') do
    %i.nc-icon.nc-zoom-2

.myg-grid__grid.myg-grid__wrap--phone
  - @categories.each do |category|
    = render category

app/views/categories/show.html.haml
- meta title: @category.name

- replace :title do
  %h1= @category.name

%p= @category.description

%h2= t('d.packs')
.myg-grid__grid.myg-grid__wrap--phone
  - @packs.each do |pack|
    = render pack, animation: 'fadeout'